spring:
  data:
    mongodb:
      database: UserManagementDB
      host: localhost
      port: 27017  application:    name: ADMIN-SERVICE

server:  port: 8081
  
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
 